### ISSUE TITLE
Error with multibranch pipeline with parameters

### ISSUE THREAD

**Issue by fernando1989mg** [stigmelling/jenkins-action#1]
`Run stigmelling/jenkins-action@v1
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/github'
Require stack:
- /home/runner/work/_actions/stigmelling/jenkins-action/v1/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/stigmelling/jenkins-action/v1/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/stigmelling/jenkins-action/v1/index.js'
  ]
}`

**Comment by casmith** [comment]
I'm having exactly the same problem
